#!/usr/bin/env bash

export HISTCONTROL='ignoredups'
export HISTSIZE=100000
export HISTTIMEFORMAT="%F %T "
unset MAILCHECK

eval "$(dircolors --bourne-shell)"
export PYTHONDONTWRITEBYTECODE='1'

# Interactive shells only
if [[ $- =~ i ]]; then
  bind Space:magic-space
  stty -ixon # disable XON/XOFF flow control
  source ~/.config/bash/prompt.bash
fi

shopt -s histappend
shopt -s extglob

alias less='less -R'
alias grep='grep --color=auto'
alias ls='ls --color=auto --classify'

if [[ -f /usr/share/bash-completion/bash_completion ]]; then
  source /usr/share/bash-completion/bash_completion
fi

if which kubectl &>/dev/null; then
  source <(kubectl completion bash)
fi

if which direnv &>/dev/null; then
  eval "$(direnv hook bash)"
fi

function cd() {
  if [[ $# == 0 ]]; then
    builtin cd ~ && ls
  else
    builtin cd "$*" && ls
  fi
}
. "$HOME/.cargo/env"
